version: '3.9'

services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    command: uvicorn app.adapters.api.rest.fastapi_app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - default
  
  db:
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default

  redis:
    image: redis
    container_name: redis_cache
    ports:
      - "6379:6379"
    restart: always
    networks:
      - default

volumes:
  postgres_data:

networks:
  default:
    driver: bridge
